stages:
  - packages
  - build
  - sign

packages:
  stage: packages
  image: registry.fedoraproject.org/fedora:latest
  variables:
    OUTPUT_DIR: /tmp/built-packages
  script:
    - sh packages/build.sh
    - cp /tmp/built-packages/* files
  artifacts:
    untracked: true

build:
  stage: build
  dependencies:
    - packages
  image: quay.io/containers/buildah:latest
  before_script:
    # Login to the container registry.
    - buildah login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    # Build the image.
    - buildah build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    # Push the image to the container registry.
    - buildah push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - buildah push $CI_REGISTRY_IMAGE:latest

sign:
  stage: sign
  dependencies:
    - build
  image: quay.io/containers/podman:latest
  before_script:
    # Install Cosign.
    - COSIGN_VERSION=$(curl -s https://api.github.com/repos/sigstore/cosign/releases/latest | grep tag_name | cut -d ":" -f2 | tr -d "v\", ")
    - curl -O -L "https://github.com/sigstore/cosign/releases/latest/download/cosign-${COSIGN_VERSION}.x86_64.rpm"
    - rpm -ivh cosign-${COSIGN_VERSION}.x86_64.rpm
    # Login to the container registry.
    - cosign login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    # Get the image digest.
    - podman pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - IMAGE_DIGEST=$(podman inspect --format='{{index .RepoDigests 0}}' $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA)
    # Sign the image.
    - cosign sign -y --key $COSIGN_PRIVATE_KEY $IMAGE_DIGEST
