stages:
  - build
  - sign

build:
  stage: build
  image: quay.io/containers/buildah:latest
  before_script:
    - export REGISTRY_AUTH_FILE=$HOME/auth.json
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - buildah pull $CI_REGISTRY_IMAGE:latest || true
    - buildah build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest --cache-from $CI_REGISTRY_IMAGE .
    - buildah push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - buildah push $CI_REGISTRY_IMAGE:latest

sign:
  stage: sign
  image: gcr.io/projectsigstore/cosign:latest
  script:
    - cosign sign -y --key $COSIGN_PRIVATE_KEY $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - cosign sign -y --key $COSIGN_PRIVATE_KEY $CI_REGISTRY_IMAGE:latest
