name: ISO
on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed
  workflow_dispatch:

jobs:
  generate-tags:
    name: Generate tags
    runs-on: ubuntu-24.04

    outputs:
      tags: "${{ steps.generate-tag.outputs.tags }}"

    steps:
      - name: Generate tag
        id: generate-tag
        shell: bash
        run: |
          TAGS=()
          TIMESTAMP="$(date +%Y%m%d)"

          SHA_SHORT="${GITHUB_SHA::7}"
          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"

          PR_TAG="pr-${{ github.event.number }}"
          COMMIT_TAG="${SHA_SHORT}"

          BUILD_TAG="${TIMESTAMP}"
          LATEST_TAG="latest"

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              TAGS+=("${PR_TAG}")
              TAGS+=("${COMMIT_TAG}")
          else
              TAGS+=("${LATEST_TAG}")
              #TAGS+=("${TIMESTAMP}")
          fi

          echo "tags=$(jq -nc '$ARGS.positional' --args ${TAGS[@]})" >> $GITHUB_OUTPUT

  generate-iso:
    name: Generate an ISO image
    runs-on: ubuntu-24.04
    needs: generate-tags
    strategy:
      matrix:
        tag: "${{ fromJSON(needs.generate-tags.outputs.tags) }}"

    steps:
      - name: Build ISO
        uses: jasonn3/build-container-installer@main
        id: iso-build
        with:
          image_name: "${{ github.event.repository.name }}"
          image_repo: "ghcr.io/${{ github.repository_owner }}"
          image_tag: "${{ matrix.tag }}"
          variant: "Silverblue"
          iso_name: "${{ github.event.repository.name }}-${{ matrix.tag }}.iso"

      - name: Upload ISO as artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.iso-build.outputs.iso_name }}
          path: |
            ${{ steps.build.outputs.iso_path }}
            ${{ steps.build.outputs.iso_path }}-CHECKSUM
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
