name: ISO
on:
  workflow_dispatch:

jobs:
  generate-iso:
    name: Generate an ISO image
    runs-on: ubuntu-24.04

    steps:
      - name: Generate tag
        id: generate-tag
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
              tag="${{ github.ref_name }}"
          else
              tag="latest"
          fi

          echo "tag=${tag}" >> $GITHUB_OUTPUT

      - name: Build ISO
        uses: jasonn3/build-container-installer@main
        id: iso-build
        with:
          image_name: "${{ github.event.repository.name }}"
          image_repo: "ghcr.io/${{ github.repository_owner }}"
          image_tag: "${{ steps.generate-tag.outputs.tag }}"
          variant: "Silverblue"
          iso_name: "${{ github.event.repository.name }}-${{ matrix.tag }}.iso"

      - name: Upload ISO as artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: "${{ steps.iso-build.outputs.iso_name }}"
          path: "${{ steps.build.outputs.iso_path }}"
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
